{{- $publicIP := .Values.publicIP }}
{{- $trustedProxies := .Values.trustedProxies }}
{{- $sourceInterface := .Values.deployment.init.sourceInterface }}
{{- $dhcpInterfaceType := .Values.deployment.init.interfaceMode }}
{{- if .Values.deployment.daemonSet.enabled }}
apiVersion: apps/v1
kind: DaemonSet
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- if not .Values.deployment.daemonSet.enabled }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      stack: tinkerbell
      {{- with .Values.deployment.selector }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  {{- if not .Values.deployment.daemonSet.enabled }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        stack: tinkerbell
        {{- with .Values.deployment.selector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: tinkerbell
          image: {{ .Values.deployment.image }}:{{ coalesce .Values.deployment.imageTag .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          {{- range .Values.deployment.additionalArgs }}
          args:
            - {{ . }}
          {{- end }}
          env:
          # RUFIO
            - name: TINKERBELL_RUFIO_CONTROLLER_ENABLE_LEADER_ELECTION
              value: {{ .Values.deployment.envs.rufio.enableLeaderElection | quote }}
            - name: TINKERBELL_RUFIO_CONTROLLER_LEADER_ELECTION_NAMESPACE
              value: {{ .Values.deployment.envs.rufio.leaderElectionNamespace | quote }}
            - name: TINKERBELL_RUFIO_CONTROLLER_LOG_LEVEL
              value: {{ .Values.deployment.envs.rufio.logLevel | quote }}
            - name: TINKERBELL_RUFIO_CONTROLLER_METRICS_ADDR
              value: {{ .Values.deployment.envs.rufio.metricsAddr | quote }}
            - name: TINKERBELL_RUFIO_CONTROLLER_PROBE_ADDR
              value: {{ .Values.deployment.envs.rufio.probeAddr | quote }}
            - name: TINKERBELL_RUFIO_BMC_CONNECT_TIMEOUT
              value: {{ .Values.deployment.envs.rufio.bmcConnectTimeout | quote }}
            - name: TINKERBELL_RUFIO_POWER_CHECK_INTERVAL
              value: {{ .Values.deployment.envs.rufio.powerCheckInterval | quote }}
          # TINK CONTROLLER
            - name: TINKERBELL_TINK_CONTROLLER_ENABLE_LEADER_ELECTION
              value: {{ .Values.deployment.envs.tinkController.enableLeaderElection | quote }}
            - name: TINKERBELL_TINK_CONTROLLER_LEADER_ELECTION_NAMESPACE
              value: {{ .Values.deployment.envs.tinkController.leaderElectionNamespace | quote }}
            - name: TINKERBELL_TINK_CONTROLLER_LOG_LEVEL
              value: {{ .Values.deployment.envs.tinkController.logLevel | quote }}
            - name: TINKERBELL_TINK_CONTROLLER_METRICS_ADDR
              value: {{ .Values.deployment.envs.tinkController.metricsAddr | quote }}
            - name: TINKERBELL_TINK_CONTROLLER_PROBE_ADDR
              value: {{ .Values.deployment.envs.tinkController.probeAddr | quote }}
          # TINK SERVER
            - name: TINKERBELL_TINK_SERVER_BIND_ADDR
              value: {{ .Values.deployment.envs.tinkServer.bindAddr | quote }}
            - name: TINKERBELL_TINK_SERVER_BIND_PORT
              value: {{ .Values.deployment.envs.tinkServer.bindPort | quote }}
            - name: TINKERBELL_TINK_SERVER_LOG_LEVEL
              value: {{ .Values.deployment.envs.tinkServer.logLevel | quote }}
            - name: TINKERBELL_TINK_SERVER_AUTO_ENROLLMENT_ENABLED
              value: {{ .Values.deployment.envs.tinkServer.autoEnrollmentEnabled | quote }}
            - name: TINKERBELL_TINK_SERVER_AUTO_DISCOVERY_ENABLED
              value: {{ .Values.deployment.envs.tinkServer.autoDiscoveryEnabled | quote }}
            - name: TINKERBELL_TINK_SERVER_AUTO_DISCOVERY_NAMESPACE
              value: {{ coalesce .Values.deployment.envs.tinkServer.autoDiscoveryNamespace .Release.Namespace | quote }}
            - name: TINKERBELL_TINK_SERVER_AUTO_DISCOVERY_AUTO_ENROLLMENT_ENABLED
              value: {{ .Values.deployment.envs.tinkServer.autoDiscoveryAutoEnrollmentEnabled | quote }}
          # TOOTLES
            - name: TINKERBELL_TOOTLES_BIND_ADDR
              value: {{ .Values.deployment.envs.tootles.bindAddr | quote }}
            - name: TINKERBELL_TOOTLES_BIND_PORT
              value: {{ .Values.deployment.envs.tootles.bindPort | quote }}
            - name: TINKERBELL_TOOTLES_DEBUG_MODE
              value: {{ .Values.deployment.envs.tootles.debugMode | quote }}
            - name: TINKERBELL_TOOTLES_LOG_LEVEL
              value: {{ .Values.deployment.envs.tootles.logLevel | quote }}
          # SMEE
            - name: TINKERBELL_DHCP_ENABLED
              value: {{ .Values.deployment.envs.smee.dhcpEnabled | quote }}
            - name: TINKERBELL_DHCP_MODE
              value: {{ .Values.deployment.envs.smee.dhcpMode | quote }}
            - name: TINKERBELL_DHCP_BIND_ADDR
              value: {{ .Values.deployment.envs.smee.dhcpBindAddr | quote }}
            - name: TINKERBELL_DHCP_BIND_INTERFACE
              value: {{ .Values.deployment.envs.smee.dhcpBindInterface | quote }}
            - name: TINKERBELL_DHCP_IP_FOR_PACKET
              value: {{ .Values.deployment.envs.smee.dhcpIPForPacket | quote }}
            - name: TINKERBELL_DHCP_SYSLOG_IP
              value: {{ .Values.deployment.envs.smee.dhcpSyslogIP | quote }}
            - name: TINKERBELL_DHCP_TFTP_IP
              value: {{ .Values.deployment.envs.smee.dhcpTftpIP | quote }}
            - name: TINKERBELL_DHCP_TFTP_PORT
              value: {{ .Values.deployment.envs.smee.dhcpTftpPort | quote }}
            - name: TINKERBELL_DHCP_IPXE_HTTP_SCRIPT_PREPEND_MAC
              value: {{ .Values.deployment.envs.smee.dhcpIpxeHttpScriptPrependMac | quote }}
            - name: TINKERBELL_DHCP_IPXE_HTTP_BINARY_SCHEME
              value: {{ .Values.deployment.envs.smee.dhcpIpxeHttpBinaryScheme | quote }}
            - name: TINKERBELL_DHCP_IPXE_HTTP_BINARY_HOST
              value: {{ .Values.deployment.envs.smee.dhcpIpxeHttpBinaryHost | quote }}
            - name: TINKERBELL_DHCP_IPXE_HTTP_BINARY_PORT
              value: {{ .Values.deployment.envs.smee.dhcpIpxeHttpBinaryPort | quote }}
            - name: TINKERBELL_DHCP_IPXE_HTTP_BINARY_PATH
              value: {{ .Values.deployment.envs.smee.dhcpIpxeHttpBinaryPath | quote }}
            - name: TINKERBELL_DHCP_IPXE_HTTP_SCRIPT_SCHEME
              value: {{ .Values.deployment.envs.smee.dhcpIpxeHttpScriptScheme | quote }}
            - name: TINKERBELL_DHCP_IPXE_HTTP_SCRIPT_HOST
              value: {{ .Values.deployment.envs.smee.dhcpIpxeHttpScriptHost | quote }}
            - name: TINKERBELL_DHCP_IPXE_HTTP_SCRIPT_PORT
              value: {{ .Values.deployment.envs.smee.dhcpIpxeHttpScriptPort | quote }}
            - name: TINKERBELL_DHCP_IPXE_HTTP_SCRIPT_PATH
              value: {{ .Values.deployment.envs.smee.dhcpIpxeHttpScriptPath | quote }}
            - name: TINKERBELL_IPXE_BINARY_INJECT_MAC_ADDR_FORMAT
              value: {{ .Values.deployment.envs.smee.ipxeBinaryInjectMacAddrFormat | quote }}
            - name: TINKERBELL_IPXE_EMBEDDED_SCRIPT_PATCH
              value: {{ .Values.deployment.envs.smee.ipxeEmbeddedScriptPatch | quote }}
            - name: TINKERBELL_IPXE_HTTP_BINARY_ENABLED
              value: {{ .Values.deployment.envs.smee.ipxeHttpBinaryEnabled | quote }}
            - name: TINKERBELL_IPXE_HTTP_SCRIPT_ENABLED
              value: {{ .Values.deployment.envs.smee.ipxeHttpScriptEnabled | quote }}
            - name: TINKERBELL_IPXE_HTTP_SCRIPT_BIND_ADDR
              value: {{ .Values.deployment.envs.smee.ipxeHttpScriptBindAddr | quote }}
            - name: TINKERBELL_IPXE_HTTP_SCRIPT_BIND_PORT
              value: {{ .Values.deployment.envs.smee.ipxeHttpScriptBindPort | quote }}
            - name: TINKERBELL_IPXE_HTTP_SCRIPT_EXTRA_KERNEL_ARGS
              value: {{ join " " ( append .Values.deployment.envs.smee.ipxeHttpScriptExtraKernelArgs ( printf "tink_worker_image=%s:%s" .Values.deployment.agentImage (coalesce .Values.deployment.agentImageTag .Chart.AppVersion) ) ) | quote }}
            - name: TINKERBELL_IPXE_SCRIPT_TRUSTED_PROXIES
              value: {{ coalesce .Values.deployment.envs.smee.ipxeHttpScriptTrustedProxies ( join "," $trustedProxies ) | quote }}
            - name: TINKERBELL_IPXE_HTTP_SCRIPT_RETRIES
              value: {{ .Values.deployment.envs.smee.ipxeHttpScriptRetries | quote }}
            - name: TINKERBELL_IPXE_HTTP_SCRIPT_RETRY_DELAY
              value: {{ .Values.deployment.envs.smee.ipxeHttpScriptRetryDelay | quote }}
            - name: TINKERBELL_IPXE_HTTP_SCRIPT_OSIE_URL
              value: {{ coalesce .Values.artifactsFileServer .Values.deployment.envs.smee.ipxeHttpScriptOsieURL | quote }}
            - name: TINKERBELL_ISO_ENABLED
              value: {{ .Values.deployment.envs.smee.isoEnabled | quote }}
            - name: TINKERBELL_ISO_UPSTREAM_URL
              value: {{ .Values.deployment.envs.smee.isoUpstreamURL | quote }}
            - name: TINKERBELL_ISO_PATCH_MAGIC_STRING
              value: {{ .Values.deployment.envs.smee.isoPatchMagicString | quote }}
            - name: TINKERBELL_ISO_STATIC_IPAM_ENABLED
              value: {{ .Values.deployment.envs.smee.isoStaticIPAMEnabled | quote }}
            - name: TINKERBELL_SMEE_LOG_LEVEL
              value: {{ .Values.deployment.envs.smee.logLevel | quote }}
            - name: TINKERBELL_SYSLOG_ENABLED
              value: {{ .Values.deployment.envs.smee.syslogEnabled | quote }}
            - name: TINKERBELL_SYSLOG_BIND_ADDR
              value: {{ .Values.deployment.envs.smee.syslogBindAddr | quote }}
            - name: TINKERBELL_SYSLOG_BIND_PORT
              value: {{ .Values.deployment.envs.smee.syslogBindPort | quote }}
            - name: TINKERBELL_TFTP_SERVER_ENABLED
              value: {{ .Values.deployment.envs.smee.tftpServerEnabled | quote }}
            - name: TINKERBELL_TFTP_SERVER_BIND_ADDR
              value: {{ .Values.deployment.envs.smee.tftpServerBindAddr | quote }}
            - name: TINKERBELL_TFTP_SERVER_BIND_PORT
              value: {{ .Values.deployment.envs.smee.tftpServerBindPort | quote }}
            - name: TINKERBELL_TFTP_TIMEOUT
              value: {{ .Values.deployment.envs.smee.tftpTimeout | quote }}
            - name: TINKERBELL_TFTP_BLOCK_SIZE
              value: {{ .Values.deployment.envs.smee.tftpBlockSize | quote }}
            - name: TINKERBELL_IPXE_SCRIPT_TINK_SERVER_ADDR_PORT
              value: {{ .Values.deployment.envs.smee.ipxeScriptTinkServerAddrPort | quote }}
            - name: TINKERBELL_IPXE_SCRIPT_TINK_SERVER_USE_TLS
              value: {{ .Values.deployment.envs.smee.ipxeScriptTinkServerUseTLS | quote }}
            - name: TINKERBELL_IPXE_SCRIPT_TINK_SERVER_INSECURE_TLS
              value: {{ .Values.deployment.envs.smee.ipxeScriptTinkServerInsecureTLS | quote }}
          # SECONDSTAR
            - name: TINKERBELL_SECONDSTAR_PORT
              value: {{ .Values.deployment.envs.secondstar.bindPort | quote }}
            - name: TINKERBELL_SECONDSTAR_HOST_KEY
              value: {{ .Values.deployment.envs.secondstar.hostKeyPath | quote }}
            - name: TINKERBELL_SECONDSTAR_IPMITOOL_PATH
              value: {{ .Values.deployment.envs.secondstar.ipmitoolPath | quote }}
            - name: TINKERBELL_SECONDSTAR_IDLE_TIMEOUT
              value: {{ .Values.deployment.envs.secondstar.idleTimeout | quote }}
            - name: TINKERBELL_SECONDSTAR_LOG_LEVEL
              value: {{ .Values.deployment.envs.secondstar.logLevel | quote }}
          # GLOBALS
            - name: TINKERBELL_LOG_LEVEL
              value: {{ .Values.deployment.envs.globals.logLevel | quote }}
            - name: TINKERBELL_BACKEND
              value: {{ .Values.deployment.envs.globals.backend | quote }}
            - name: TINKERBELL_BACKEND_FILE_PATH
              value: {{ .Values.deployment.envs.globals.backendFilePath | quote }}
            - name: TINKERBELL_BACKEND_KUBE_BURST
              value: {{ .Values.deployment.envs.globals.backendKubeBurst | quote }}
            - name: TINKERBELL_BACKEND_KUBE_CONFIG
              value: {{ .Values.deployment.envs.globals.backendKubeConfig | quote }}
            - name: TINKERBELL_BACKEND_KUBE_NAMESPACE
              value: {{ .Values.deployment.envs.globals.backendKubeNamespace | quote }}
            - name: TINKERBELL_BACKEND_KUBE_QPS
              value: {{ .Values.deployment.envs.globals.backendKubeQPS | quote }}
            - name: TINKERBELL_OTEL_ENDPOINT
              value: {{ .Values.deployment.envs.globals.otelEndpoint | quote }}
            - name: TINKERBELL_OTEL_INSECURE
              value: {{ .Values.deployment.envs.globals.otelInsecure | quote }}
            - name: TINKERBELL_TRUSTED_PROXIES
              value: {{ ( join "," $trustedProxies ) | quote }}
            - name: TINKERBELL_PUBLIC_IPV4
              value: {{ (coalesce .Values.deployment.envs.globals.publicIpv4 $publicIP) | quote }}
            - name: TINKERBELL_ENABLE_SMEE
              value: {{ .Values.deployment.envs.globals.enableSmee | quote }}
            - name: TINKERBELL_ENABLE_TOOTLES
              value: {{ .Values.deployment.envs.globals.enableTootles | quote }}
            - name: TINKERBELL_ENABLE_TINK_SERVER
              value: {{ .Values.deployment.envs.globals.enableTinkServer | quote }}
            - name: TINKERBELL_ENABLE_TINK_CONTROLLER
              value: {{ .Values.deployment.envs.globals.enableTinkController | quote }}
            - name: TINKERBELL_ENABLE_RUFIO_CONTROLLER
              value: {{ .Values.deployment.envs.globals.enableRufioController | quote }}
            - name: TINKERBELL_ENABLE_SECONDSTAR
              value: {{ .Values.deployment.envs.globals.enableSecondstar | quote }}
            - name: TINKERBELL_ENABLE_CRD_MIGRATIONS
              value: {{ .Values.deployment.envs.globals.enableCRDMigrations | quote }}
            {{- with .Values.deployment.additionalEnvs }}
          # Additional environment variables
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
          {{- if .Values.deployment.envs.globals.enableSmee }}
            - containerPort: {{ .Values.deployment.envs.smee.tftpServerBindPort }}
            {{- with .Values.service.ports.tftp }}
              name: {{ .name }}
              protocol: {{ .protocol }}
            {{- end }}
            - containerPort: {{ .Values.deployment.envs.smee.syslogBindPort }}
            {{- with .Values.service.ports.syslog }}
              name: {{ .name }}
              protocol: {{ .protocol }}
            {{- end }}
            {{- with .Values.service.ports.dhcp }}
            - containerPort: {{ .port }}
              name: {{ .name }}
              protocol: {{ .protocol }}
            {{- end }}
            - containerPort: {{ .Values.deployment.envs.smee.ipxeHttpScriptBindPort }}
            {{- with .Values.service.ports.httpSmee }}
              name: {{ .name }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- end }}
          {{- if .Values.deployment.envs.globals.enableTootles }}
            - containerPort: {{ .Values.deployment.envs.tootles.bindPort }}
            {{- with .Values.service.ports.httpTootles }}
              name: {{ .name }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- end }}
          {{- if .Values.deployment.envs.globals.enableTinkServer }}
            - containerPort: {{ .Values.deployment.envs.tinkServer.bindPort }}
            {{- with .Values.service.ports.grpc }}
              name: {{ .name }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- end }}
          {{- if .Values.deployment.envs.globals.enableSecondstar }}
            - containerPort: {{ .Values.deployment.envs.secondstar.bindPort }}
            {{- with .Values.service.ports.ssh }}
              name: {{ .name }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- end }}
          resources: {{ toYaml .Values.deployment.resources | nindent 12 }}
          securityContext:
            capabilities:
              add:
                - NET_RAW
          {{- with .Values.deployment.volumeMounts }}
          volumeMounts:
          {{- toYaml . | nindent 10 }}
          {{- end }}
      hostNetwork: {{ .Values.deployment.hostNetwork }}
      serviceAccountName: {{ .Values.rbac.name }}-service-account
      volumes:
      {{- if .Values.deployment.init.enabled }}
      - name: script
        configMap:
          name: host-interface-script
          defaultMode: 0500
      {{- end }}
      {{- with  .Values.deployment.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.init.enabled }}
      hostPID: true
      {{- end }}
      {{- if .Values.deployment.init.enabled }}
      initContainers:
      - name: broadcast-interface
        image: {{ .Values.deployment.init.image }}
        command: ["/script/host_interface.sh", "-s", "{{ $sourceInterface }}", "-t", "{{ $dhcpInterfaceType }}"]
        volumeMounts:
            - name: script
              mountPath: "/script"
        securityContext:
          privileged: true
      {{- end }}
