{{- if .Values.rbac.secrets.enabled }}

apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.rbac.type }}
metadata:
  name: {{ .Values.rbac.name }}-secrets
  {{- if eq .Values.rbac.type "Role" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

{{- end }}
