{{- if .Values.optional.hookos.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.optional.hookos.name}}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      {{- with .Values.optional.hookos.selector }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  replicas: 1
  strategy:
    type: {{ .Values.optional.hookos.deployment.strategy.type }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/hookos/nginx-configmap.yaml") . | sha256sum }}
        checksum/download-hook: {{ include (print $.Template.BasePath "/hookos/download-configmap.yaml") . | sha256sum }}
      labels:
        {{- with .Values.optional.hookos.selector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.optional.hookos.name }}
        image: {{ .Values.optional.hookos.image }}
        ports:
        - containerPort: {{ .Values.optional.hookos.port }}
          protocol: TCP
          name: hook-http
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /etc/nginx
          readOnly: true
          name: nginx-conf
        - mountPath: /usr/share/nginx/html
          name: hook-artifacts
      - name: download-hook
        image: {{ .Values.optional.hookos.scriptImage }}
        command: ["/script/entrypoint.sh"]
        args: ["--url", "{{ .Values.optional.hookos.downloadURL }}", "--output-dir", "/output", "--arch", "{{ .Values.optional.hookos.arch }}", "--version", "{{ .Values.optional.hookos.kernelVersion }}", "--ext", "{{ .Values.optional.hookos.extension }}"]
        volumeMounts:
          - mountPath: /output
            name: hook-artifacts
          - mountPath: /script
            name: configmap-volume
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: hook-artifacts
        persistentVolumeClaim:
          claimName: {{ coalesce .Values.optional.hookos.persistence.existingClaim .Values.optional.hookos.persistence.localPersistentVolume.name }}
      - name: configmap-volume
        configMap:
          defaultMode: 0700
          name: download-hook
      hostNetwork: {{ .Values.optional.hookos.hostNetwork }}
      {{- with .Values.optional.hookos.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.optional.hookos.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.optional.hookos.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
